//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyBudgetApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class MemberExpense: INotifyPropertyChanged
    {
        public int id { get; set; }
        public int memberId { get; set; }
        public int expenseId { get; set; }
        //public double sharePercentage { get; set; }

        private double sharePercentage1;
        public double sharePercentage
        {
            get { return sharePercentage1; }
            set
            {
                if (sharePercentage1 != value)
                {
                    sharePercentage1 = value;
                    OnPropertyChanged(nameof(sharePercentage));
                }
            }
        }
        public double amount { get; set; }
    
        public virtual Expense Expense { get; set; }
        public virtual Member Member { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
