//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyBudgetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberIncome
    {
        public int id { get; set; }
        public int memberId { get; set; }
        public int incomeId { get; set; }
        public double sharePercentage { get; set; }
        public double memberAmount { get; set; }
    
        public virtual Income Income { get; set; }
        public virtual Member Member { get; set; }
    }
}
